modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_world"
version="1.0.0"
displayName="The World"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ambro, MCreator"

[[dependencies.the_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




